# Configuration constants for the evolutionary algorithm
MAX_POPULATION_SIZE = 1_000_000
MAX_CHROMOSOME_LENGTH = 10_000
MAX_CHARS = 4_000
DEFAULT_PARALLEL_AGENTS = 10
STATS_WINDOW_SIZE = 100

# Constants for test task
TEST_OPTIMAL_LENGTH = 23
TEST_TOKEN_LIMIT = 40
